[versions]
kotlinVersion = "1.8.10"
mokoResourcesVersion = "0.22.0"
mokoMediaVersion = "0.11.0"
mokoTensorflowVersion = "0.3.0"

coroutinesVersion = "1.7.0"

tensorflowLiteVersion = "2.12.0"
coreKtxVersion = "1.10.1"
playServicesVersion = "18.0.2"
androidDrawVersion = "v0.1"
lifecycleRuntimeVersion = "2.6.1"
# Tests
tests-junit-core = "4.13.2"
tests-junit-ext = "1.1.5"

[libraries]
# Tests
tests-junit = { module = "junit:junit", version.strictly = "4.13.2" }
tests-junitExt = { module = "androidx.test.ext:junit", version.strictly = "1.1.5" }
tests-espressoCore = { module = "androidx.test.espresso:espresso-core", version.strictly = "3.5.1" }
appCompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
kotlinStdLib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinVersion" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
playServices = { module = "com.google.android.gms:play-services-tasks", version.ref = "playServicesVersion" }
androidDraw = { module = "com.github.divyanshub024:AndroidDraw", version.ref = "androidDrawVersion" }
tensorflowLite = { module = "org.tensorflow:tensorflow-lite", version.ref = "tensorflowLiteVersion" }
mokoTensorflow = { module = "dev.icerock.moko:tensorflow", version.ref = "mokoTensorflowVersion" }
mokoResources = { module = "dev.icerock.moko:resources", version.ref = "mokoResourcesVersion" }
mokoMedia = { module = "dev.icerock.moko:media", version.ref = "mokoMediaVersion" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinesVersion" }
lifecycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeVersion" }

mokoResourcesGenerator = { module = "dev.icerock.moko:resources-generator", version.ref = "mokoResourcesVersion" }
mokoMultiplatformPlugin = { module = "dev.icerock:mobile-multiplatform", version = "0.14.2" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion" }
androidGradlePlugin = { module = "com.android.tools.build:gradle", version = "7.4.2" }
detektGradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version = "1.22.0" }
mokoGradlePlugin = { module = "dev.icerock.moko:moko-gradle-plugin", version = "0.3.0" }
